config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  mount ShopifyApp::Engine, at: '/'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    unlock: 'users/unlock',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations'
  }

  get 'customer_details/index'

  resources :earning_rules

  root to: 'earning_rules#index'

  get 'exceptions/show'

  controller :mandatory_webhooks do
    post '/webhooks/shop_redact' => :shop_redact
    post '/webhooks/customers_redact' => :customer_redact
    post '/webhooks/customers_data_request' => :customers_data_request
  end

  resources :webhooks, only: [] do
    collection do
      post :orders_paid
    end
  end
end

app/models/earning_rule.rb
# frozen_string_literal: true

class EarningRule < ApplicationRecord

  belongs_to :user
  belongs_to :shop

  validates :name, presence: true
  validates :point, presence: true

  scope :order_rule, ->(shop) { where(shop: shop, status: 'true', name: 'Order').pick(:point) }
end

app/controllers/earning_rules_controller.rb
# frozen_string_literal: true

class EarningRulesController < AuthenticatedController
  include StrictQueries::Concern

  before_action :set_earning_rule, only: %i[show edit update destroy]
  before_action :authenticate_user!

  def index
    earning_rules = current_user.earning_rules.load

    if earning_rules.empty?
      redirect_to new_earning_rule_url, notice: 'Kindly create Earning Rule before you can proceed'
    else
      @earning_rules = earning_rules
    end
  end

  def show; end

  def new
    @earning_rule = current_user.earning_rules.new
  end

  def edit; end

  def create
    @earning_rule = current_user.earning_rules.new(earning_rule_params)
    @earning_rule.shop = current_shop

    respond_to do |format|
      if @earning_rule.save
        format.html { redirect_to root_path, notice: 'Earning rule was successfully created.' }
        format.json { render :show, status: :created, location: @earning_rule }
      else
        format.html { render :new }
        format.json { render json: @earning_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @earning_rule.update(earning_rule_params)
        format.html { redirect_to root_path, notice: 'Earning rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @earning_rule }
      else
        format.html { render :edit }
        format.json { render json: @earning_rule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @earning_rule.destroy
    respond_to do |format|
      format.js { redirect_to root_path, notice: 'Earning rule was successfully destroyed.' }
      format.html { redirect_to earning_rules_url, notice: 'Earning rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_earning_rule
    @earning_rule = EarningRule.find(params[:id])
  end

  def earning_rule_params
    params.require(:earning_rule).permit(:user_id, :shop_id, :name, :point, :status)
  end
end

app/views/earning_rules/_earning_rule.html.erb
<% present(earning_rule) do |earning_rule| %>
  <tr>
    <td><%= link_to earning_rule.name, edit_earning_rule_path(earning_rule) %></td>
    <td><%= earning_rule.point %></td>
    <td><%= text_formatter(earning_rule.status, 'success', 'danger') %></td>
    <td><%= link_to t('earning_rule_page.table_heading.button_labels.delete'), earning_rule, method: :delete, data: { confirm: t('earning_rule_page.table_heading.messages.delete'), remote: true }, class: 'delete btn btn-danger btn-sm' %></td>
  </tr>
<% end %>

app/views/earning_rules/_form.html.erb
<div class="container mt-5">
  <%= simple_form_for earning_rule do |f| %>
    <%= flash_messages_for(@earning_rule) %>

    <div class="row">
      <div class="col-sm-8 mb-3">
        <div class="card border-secondary">
          <div class="card-body">
            <h5 class="card-title"><%= t('earning_rule_page.form.name_heading') %></h5>
            <div class="form-inputs">
              <%= f.input :name %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-sm-4 d-none d-md-block">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= t('earning_rule_page.form.hint_heading') %></h5>
            <p class="card-text"><%= t('earning_rule_page.form.hint_text') %></p>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-8 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= t('earning_rule_page.form.point_heading') %></h5>
            <div class="form-inputs">
              <%= f.input :point %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-8 mb-3">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title"><%= t('earning_rule_page.form.checkbox_heading') %></h5>
            <div class="form-inputs">
              <%= f.check_box :status, as: :boolean, checked_value: true, unchecked_value: false %>
              <span><%= t('earning_rule_page.form.checkbox_text') %></span>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          <p><%= t('earning_rule_page.form.muted_text') %></p>
        </div>
      </div>
    </div>

    <div class="row align-items-center mb-5">
      <div class="col-6"></div>
      <div class="col-6">
        <div class="mb-3">
          <div class="form-actions">
            <%= f.button :submit, class: 'btn btn-info btn-sm float-right ml-auto' %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/earning_rules/destroy.js.erb
$('.delete').bind('ajax:success', function () {
    $(this).closest('tr').fadeOut();
})

app/views/earning_rules/edit.html.erb
<div class="container mt-5">
  <div class="row align-items-center">
    <div class="col-6">
      <h5>
        <%= t('earning_rule_page.edit_form.title') %>
      </h5>
    </div>
    <div class="col-6">
      <%= link_to 'Back', earning_rules_path, class: "btn btn-info btn-sm float-right" %>
    </div>
  </div>
</div>

<%= render 'form', earning_rule: @earning_rule %>

app/views/earning_rules/index.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
      ShopifyApp.ready(function(){
          ShopifyApp.Bar.initialize({ title: "Home" });
      });
  </script>
<% end %>

<%= render 'shared/home_banner_section' %>

<section class="mt-5 mb-3">
  <div class="container">
    <%= flash_messages_for(@earning_rule) %>

    <div class="row align-items-center">
      <div class="col-6 mt-1">
        <h5 class="active-event-title">
          <%= t('earning_rule_page.table_heading.title') %>
        </h5>
      </div>

      <div class="col-6">
        <div class="mb-3">
          <%= link_to t('earning_rule_page.table_heading.button_labels.new'), new_earning_rule_path, class: 'btn btn-info btn-sm float-right ml-auto' %>
        </div>
      </div>
    </div>

    <br>

    <div class="row">
      <div class="col-md-12">
        <table class="table table-bordered table-hover">
          <thead>
            <tr>
              <th><%= t('earning_rule_page.index_page.name') %></th>
              <th><%= t('earning_rule_page.index_page.point') %></th>
              <th><%= t('earning_rule_page.index_page.status') %></th>
              <th><%= t('earning_rule_page.index_page.action') %></th>
            </tr>
          </thead>

          <tbody>
            <%= render @earning_rules %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/earning_rules/new.html.erb
<div class="container mt-5">
  <div class="row align-items-center">
    <div class="col-6">
      <h5>
        <%= t('earning_rule_page.form.title') %>
      </h5>
    </div>
    <div class="col-6">
      <%= link_to 'Back', earning_rules_path, class: "btn btn-info btn-sm float-right" %>
    </div>
  </div>
</div>

<%= render 'form', earning_rule: @earning_rule %>

app/views/earning_rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @earning_rule.name %>
</p>

<p>
  <strong>Point:</strong>
  <%= @earning_rule.point %>
</p>

<p>
  <strong>Status:</strong>
  <%= @earning_rule.status %>
</p>

<%= link_to 'Edit', edit_earning_rule_path(@earning_rule) %> |
<%= link_to 'Back', earning_rules_path %>